### ISSUE TITLE
`pip install ament-black` fails on Python >= 3.12

### ISSUE THREAD

**Issue by cclauss** [botsandus/ament_black#15]
`pip install ament-black` fails with an error about uvloop.

|   Python | Linux | macOS | Windows |
|:--------:|:-----:|:-----:|:-------:|
|      3.9 |   ✅   |  ✅   |   ❌    |
|     3.10 |   ✅   |  ✅   |   ❌    |
|     3.11 |   ✅   |  ✅   |   ❌    |
|     3.12 |   ❌   |  ❌   |   ❌    |
|     3.13 |   ❌   |  ❌   |   ❌    |

GitHub Action:
```yml
name: pip_install_ament-black
on:
  push:
  pull_request
  workflow_dispatch:
    inputs:
      pypi_package:
        description: 'PyPI package to test'
        required: true

jobs:
  pip_install_ament-black:
    name: "ament-black on Py${{ matrix.python-version }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.x']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            allow-prereleases: true
      - run: pip install --upgrade pip
      - run: pip install ament-black
```
